### ISSUE TITLE
Tokenise comma separated artist names separately

### ISSUE THREAD

**Issue by kamalx** [punchagan/ukulele-tutorials#32]
So `Loy Mendonca, Shankar Mahadevan, Clinton Cerejo`
becomes 
![image](https://user-images.githubusercontent.com/94972/114377541-623c6880-9ba4-11eb-9bd9-6cd7bde5501b.png)
without pasting the names one by one.

**Comment by kamalx** [comment]
Same can be done for chords and composers too 😀

**Comment by punchagan** [comment]
Doing this for chords is slightly tricky, because we use a fixed list of chords and don't want to allow new chords to be entered, unlike artists and chords. If you really need this feature, I can try hacking in something.

**Comment by kamalx** [comment]
No, just the artists and composers is a huge help. Chords are better constrained as you designed them right now. :)
